// Bilingual copy for the generated statement PDF (ROADMAP Phase 4 — "PDF
// statement export"), kept separate from the rendering component
// (statement-template.tsx) so the wording is easy to review on its own.
// Same self-contained hu/en pattern as declaration-content.ts — the PDF
// is rendered server-side outside any next-intl request context, so it
// carries its own strings rather than reaching for the message catalog.
//
// The PDF deliberately shows BOTH languages on every label (hu / en),
// matching the declaration PDF and IDEAS.md's "bilingual statement
// display" note — a generated statement may be handed to third parties
// who read either language.

export const statementCopy = {
  title: { hu: "Havi elszámolás", en: "Monthly statement" },
  period: { hu: "Időszak", en: "Period" },
  status: { hu: "Állapot", en: "Status" },
  issuedAt: { hu: "Kiállítva", en: "Issued" },
  dueDate: { hu: "Fizetési határidő", en: "Due date" },
  property: { hu: "Ingatlan", en: "Property" },
  tenant: { hu: "Bérlő", en: "Tenant" },
  landlord: { hu: "Bérbeadó", en: "Landlord" },
  lineItemsTitle: { hu: "Tételek", en: "Line items" },
  group: {
    fixed: { hu: "Fix díjak", en: "Fixed charges" },
    metered: { hu: "Mért díjak", en: "Metered charges" },
    adjustments: { hu: "Korrekciók", en: "Adjustments" },
  },
  notCharged: { hu: "Nincs kiszámlázva", en: "Not charged" },
  total: { hu: "Fizetendő összesen", en: "Total payable" },
  paymentsTitle: { hu: "Befizetések", en: "Payments" },
  paidOn: { hu: "Befizetve", en: "Paid" },
  method: { hu: "Mód", en: "Method" },
  remaining: { hu: "Fennmaradó egyenleg", en: "Remaining balance" },
  paymentInstructionsTitle: { hu: "Fizetési adatok", en: "Payment details" },
  noPayments: { hu: "Nincs rögzített befizetés.", en: "No payments recorded." },
  generatedNote: {
    hu: "Ez a dokumentum a Flatlord rendszerből generált elszámolás. Nem minősül hivatalos számlának.",
    en: "This statement was generated by Flatlord. It is not a certified invoice.",
  },
  paymentMethod: {
    bank_transfer: { hu: "Banki átutalás", en: "Bank transfer" },
    cash: { hu: "Készpénz", en: "Cash" },
    revolut: { hu: "Revolut", en: "Revolut" },
    other: { hu: "Egyéb", en: "Other" },
  } as Record<string, { hu: string; en: string }>,
  statusLabel: {
    draft: { hu: "Piszkozat", en: "Draft" },
    issued: { hu: "Kiállítva", en: "Issued" },
    partially_paid: { hu: "Részben fizetve", en: "Partially paid" },
    paid: { hu: "Fizetve", en: "Paid" },
    overdue: { hu: "Lejárt", en: "Overdue" },
  } as Record<string, { hu: string; en: string }>,
};

export function bilingual(pair: { hu: string; en: string }): string {
  return `${pair.hu} / ${pair.en}`;
}
